# Generated by Django 5.2.1 on 2025-05-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_cover_image_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_specified', 'Not Specified')], default='not_specified', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
