# Generated by Django 5.2.1 on 2025-06-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_availability_application_expected_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='application',
            name='grade_points',
        ),
        migrations.RemoveField(
            model_name='application',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='university',
        ),
    ]
