# Generated by Django 5.2.1 on 2025-06-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_application_cover_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status_messages',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=10),
        ),
    ]
