# Generated by Django 5.2.1 on 2025-05-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_benefits_job_company_name_job_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='logo_image',
        ),
    ]
