# Generated by Django 5.2.1 on 2025-05-30 20:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_image_job_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dw2jlqwgv/image/upload/v1234567890/default_image.jpg', max_length=255, verbose_name='image'),
        ),
    ]
