# Generated by Django 5.2.1 on 2025-05-30 21:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='job',
            name='logo_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
