# Generated by Django 5.2.1 on 2025-05-27 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerstats',
            name='employer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='users.employerprofile'),
        ),
        migrations.AddField(
            model_name='jobapplicationstats',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_stats', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobview',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='jobs.job'),
        ),
        migrations.AlterUniqueTogether(
            name='jobview',
            unique_together={('job', 'ip_address')},
        ),
    ]
